[project]
name = "changelogfilegenerator"
version = "0.0.1"
description = "Change log file generator"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "icecream>=2.1.8",
    "typer>=0.20.0",
]
